name: Run Makefile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Compile palera1nLoaderTV
        run: make PLATFORM=appletvos SCHEME=palera1nLoaderTV package

      - name: Compile palera1nLoader
        run: make PLATFORM=iphoneos SCHEME=palera1nLoader package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-packages
          path: packages/
